### PR TITLE
Fix hover node

### LINKED ISSUE #64: Setting hoverConnectedEdges to false causes node hover to stop working
Having my interaction options set as 
```
interaction: {
    selectConnectedEdges: false,
    hideEdgesOnDrag: true,
    hover: true
}
```
lets me hover nodes, but it hovers the edges as well.

Setting it to:

```
interaction: {
    selectConnectedEdges: false,
    hideEdgesOnDrag: true,
    hover: true,
    hoverConnectedEdges: false
}
```

Causes node and edge hover to stop.

### PR DESCRIPTION
**Pull request by Tyler-Maclachlan**
Fix node hover breaking when hoverConnectedEdges = false

Fix #64

### CODE REVIEW

**Comment by micahstubbs** [comment]
hi @Tyler-Maclachlan thanks for the contribution!  could you run these commands to get the integration tests passing?

Once the tests are green, I'll take a look at this one.

```
cd visjs-network
yarn
yarn format
git add .
git commit -m "yarn format"
git push
```

**Comment by Tyler-Maclachlan** [comment]
Hi @micahstubbs, I've run the commands and pushed.

**Comment by micahstubbs** [comment]
nice, the tests are green!  

I'm going to try and test this out with this example https://jsbin.com/voritexeru/edit?html,js,output

from this issue comment https://github.com/visjs-community/visjs-network/issues/64#issuecomment-494665554

does that sound like the best approach to you @Tyler-Maclachlan ?

**Comment by Tyler-Maclachlan** [comment]
Sounds good to me

**Comment by Tyler-Maclachlan** [comment]
hi @micahstubbs,

Any kind of timeline on when this can get merged?

**Comment by micahstubbs** [comment]
@Tyler-Maclachlan hopefully soon 😅

**Comment by mojoaxel** [comment]
:love_letter: Thanks @Tyler-Maclachlan for your contribution!
This pull-request has been merge into https://github.com/visjs/vis-network/pull/28

**Pull request merged**
