### PR TITLE
FIX #42: Edge labels disappear when cluster is opened

### LINKED ISSUE #42: Edge labels disappear when cluster is opened
When opening a cluster, the labels of the unclustered edges are not restored.

This was originally described in the vis repo issue https://github.com/almende/vis/issues/4111

The bug was introduced in:
- vis release v4.21.0 https://github.com/almende/vis/releases/tag/v4.21.0.
- issue https://github.com/almende/vis/pull/3511
- commit https://github.com/almende/vis/commit/659f0e93cedecac1685ed831a0bd6fd5446fc81c

'label' was removed from the fields that were sent to util.selectiveDeepExtend().
The following code was added:
```javascript
    // Only copy label if it's a legal value.
    if (ComponentUtil.isValidLabel(newOptions.label)) {
      parentOptions.label = newOptions.label;
    } else {
 144:     parentOptions.label = undefined;
    }
```

Unfortunately line 144 overwrites the original label with undefined - and this causes the regression which is not equivalent to the original code that sent label into selectDeepExtend().

The solution provided in https://github.com/almende/vis/issues/4111 is to change it to:

```javascript
    // Only copy label if it's a legal value.
    if (ComponentUtil.isValidLabel(newOptions.label)) {
      parentOptions.label = newOptions.label
    }
    else if (!ComponentUtil.isValidLabel(parentOptions.label)){
      parentOptions.label = undefined;
    }
```

... which will retain the original label, provided it is valid.

PR coming.

### PR DESCRIPTION
**Pull request by channeladam**
Fixes #42.

Automated tests updated to prove the solution.

### CODE REVIEW

**Comment by micahstubbs** [comment]
thanks for the contribution @channeladam, taking a look at this now 😄

**Comment by micahstubbs** [comment]
@channeladam looks like the Travis CI build failed.  https://travis-ci.com/visjs-community/visjs-network/builds/97133771

could you run these commands to fix the build?

```bash
cd visjs-network

# install yarn js package manager, if not already installed
# https://yarnpkg.com/lang/en/docs/install/#alternatives-stable
curl -o- -L https://yarnpkg.com/install.sh | bash

# install js dependencies, if not already installed
yarn

# format code
yarn format

# add, commit, & push the result
git add .
git commit -m "yarn format"
git push
```

**Comment by channeladam** [comment]
Thanks - sorry - I didn't know about the yarn format command...

Now the build is failing with gulp...  Pretty sure I didn't cause that one! ?  :)


6.99s$ yarn add gulp
yarn add v1.3.2
...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 61 new dependencies.
...
warning "gulp" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".
0.95s$ gulp
assert.js:42
  throw new errors.AssertionError({
  ^
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/travis/build/visjs-community/visjs-network/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/travis/build/visjs-community/visjs-network/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/travis/build/visjs-community/visjs-network/gulpfile.js:200:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
The command "gulp" exited with 1.

**Comment by micahstubbs** [comment]
ah! thanks for getting this far.  will have a look. 

I bet we need to specify `gulp@3.91` in the `package.json` to get this to work.

thanks for your patience with these build issues - we're almost there.

**Comment by micahstubbs** [comment]
screen shot 2019-01-20 at 10 12 08 pm

here's that gulp failure in the Travis logs https://travis-ci.com/visjs-community/visjs-network/builds/97236784

**Comment by micahstubbs** [comment]
huh, the tests pass for me when I check out your branch locally 🤔 
```
git checkout -b channeladam-fix-cluster-open-missing-edge-labels master
git pull https://github.com/channeladam/visjs-network.git fix-cluster-open-missing-edge-labels
yarn install
yarn test
# ...
  243 passing (3s)
  4 pending

✨  Done in 4.79s.
```

**Comment by micahstubbs** [comment]
@channeladam thanks for finding this bug in our travis config 😅  with PR https://github.com/visjs-community/visjs-network/pull/49 that just went it, it should be fixed now. 

when you have a moment, could you run these commands to apply the fix to your branch?

```bash
cd visjs-network
git checkout master
git remote add upstream git@github.com:visjs-community/visjs-network.git
git pull upstream master
git checkout fix-cluster-open-missing-edge-labels
git rebase master
git push
```

---

alternately, you could also just look at the diff here and add the new line to `.travis.yml` on your branch, then commit and push the result.  https://github.com/visjs-community/visjs-network/pull/49/files

screen shot 2019-01-20 at 10 37 13 pm

**Comment by micahstubbs** [comment]
fantastic, thanks for updating this PR @channeladam 

let's get this fix in!

**Comment by mojoaxel** [comment]
:love_letter: Thanks @channeladam for your contribution!
This pull-request also has been merge into https://github.com/visjs/vis-network/pull/15

**Pull request merged**
